export interface IRuneWeight {
  runeName: string;
  imgSrc: string;
  lowValue: number;
  midValue?: number;
  highValue?: number;
  runeWeight: number;
}

export const RuneWeights: IRuneWeight[] = [
  {
    runeName: "Inteligencia",
    imgSrc: "http://fruitstar.ninja/images/runes/int.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 1,
  },
  {
    runeName: "Agilidad",
    imgSrc: "http://fruitstar.ninja/images/runes/agi.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 1,
  },
  {
    runeName: "Suerte",
    imgSrc: "http://fruitstar.ninja/images/runes/cha.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 1,
  },
  {
    runeName: "Fuerza",
    imgSrc: "http://fruitstar.ninja/images/runes/stre.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 1,
  },
  {
    runeName: "Sabiduría",
    imgSrc: "http://fruitstar.ninja/images/runes/wis.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 3,
  },
  {
    runeName: "Vitalidad",
    imgSrc: "http://fruitstar.ninja/images/runes/vit.png",
    lowValue: 3,
    midValue: 10,
    highValue: 30,
    runeWeight: 0.25,
  },
  {
    runeName: "Iniciativa",
    imgSrc: "http://fruitstar.ninja/images/runes/ini.png",
    lowValue: 10,
    midValue: 30,
    highValue: 100,
    runeWeight: 0.1,
  },
  {
    runeName: "Res fija",
    imgSrc: "http://fruitstar.ninja/images/runes/earthres.png",
    lowValue: 1,
    runeWeight: 2,
  },
  {
    runeName: "Res %",
    imgSrc: "http://fruitstar.ninja/images/runes/earthresper.png",
    lowValue: 1,
    runeWeight: 6,
  },
  {
    runeName: "Res empujes",
    imgSrc: "http://fruitstar.ninja/images/runes/pshres.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 2,
  },
  {
    runeName: "Res crítica",
    imgSrc: "http://fruitstar.ninja/images/runes/crires.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 2,
  },
  {
    runeName: "Res pérdida PA/PM",
    imgSrc: "http://fruitstar.ninja/images/runes/apres.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 7,
  },
  {
    runeName: "Daños",
    imgSrc: "http://fruitstar.ninja/images/runes/dam.png",
    lowValue: 1,
    runeWeight: 20,
  },
  {
    runeName: "Daños elementales",
    imgSrc: "http://fruitstar.ninja/images/runes/earthdam.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 5,
  },
  {
    runeName: "Daños críticos",
    imgSrc: "http://fruitstar.ninja/images/runes/cridam.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 5,
  },
  {
    runeName: "Daños empujes",
    imgSrc: "http://fruitstar.ninja/images/runes/pshdam.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 5,
  },
  {
    runeName: "PA",
    imgSrc: "http://fruitstar.ninja/images/runes/apga.png",
    lowValue: 1,
    runeWeight: 100,
  },
  {
    runeName: "PM",
    imgSrc: "http://fruitstar.ninja/images/runes/mpga.png",
    lowValue: 1,
    runeWeight: 51,
  },
  {
    runeName: "Alcance",
    imgSrc: "http://fruitstar.ninja/images/runes/range.png",
    lowValue: 1,
    runeWeight: 51,
  },
  {
    runeName: "Invocaciones",
    imgSrc: "http://fruitstar.ninja/images/runes/summo.png",
    lowValue: 1,
    runeWeight: 30,
  },
  {
    runeName: "Críticos",
    imgSrc: "http://fruitstar.ninja/images/runes/summo.png",
    lowValue: 1,
    runeWeight: 30,
  },
  {
    runeName: "Daños reenviados",
    imgSrc: "http://fruitstar.ninja/images/runes/damref.png",
    lowValue: 1,
    runeWeight: 30,
  },
  {
    runeName: "Curas",
    imgSrc: "http://fruitstar.ninja/images/runes/hea.png",
    lowValue: 1,
    runeWeight: 20,
  },
  {
    runeName: "Arma de caza",
    imgSrc: "http://fruitstar.ninja/images/runes/hunting.png",
    lowValue: 1,
    runeWeight: 5,
  },
  {
    runeName: "Pods",
    imgSrc: "http://fruitstar.ninja/images/runes/pod.png",
    lowValue: 10,
    midValue: 30,
    highValue: 100,
    runeWeight: 0.4,
  },
  {
    runeName: "Potencia",
    imgSrc: "http://fruitstar.ninja/images/runes/pow.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 2,
  },
  {
    runeName: "Prospección",
    imgSrc: "http://fruitstar.ninja/images/runes/prospe.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 3,
  },
  {
    runeName: "Daños trampas",
    imgSrc: "http://fruitstar.ninja/images/runes/tra.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 15,
  },
  {
    runeName: "% Daños trampas",
    imgSrc: "http://fruitstar.ninja/images/runes/traper.png",
    lowValue: 1,
    midValue: 3,
    highValue: 10,
    runeWeight: 2,
  },
  {
    runeName: "Placaje/Huida",
    imgSrc: "http://fruitstar.ninja/images/runes/loc.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 4,
  },
  {
    runeName: "Reducción PA/PM",
    imgSrc: "http://fruitstar.ninja/images/runes/apred.png",
    lowValue: 1,
    midValue: 3,
    runeWeight: 7,
  },
];
